# Generated by Django 5.2 on 2026-01-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('telegram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
